import 'package:flutter/material.dart';

import 'ChangeStyle.dart';

void main() {
  runApp(const Choice());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Choice extends StatelessWidget {
  const Choice({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light().copyWith(
        scaffoldBackgroundColor: Colors.white,
      ),
      home: Scaffold(
        body:
          Frame427320722(),
      ),
    );
  }
}

class Frame427320722 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width:  MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage('images/test.png'),
              fit: BoxFit.cover,
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 80,
                top: 150,
                child: Text(
                  '이미지 변환을 도와드릴게요.\n원하는 스타일을 선택해주세요.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Apple SD Gothic Neo',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 622,
                child: Container(
                  width: 358,
                  height: 56,
                  decoration: ShapeDecoration(
                    color: Color(0xFF363636),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(32.50),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 9,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 185,
                top: 637,
                child: Text(
                  '다음',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Apple SD Gothic Neo',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 285,
                child: Container(
                  width: 168,
                  height: 276,
                  decoration: BoxDecoration(
                    color: Color(0xD7FFFFFF), // Change this color to your desired background color
                   // Optional: To round the corners
                    border: Border.all(
                      width: 2,
                      color: Colors.black.withOpacity(0.30000001192092896),
                    ),

                  boxShadow: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 215,
                top: 285,
                child: Container(
                  width: 168,
                  height: 276,
                  decoration: BoxDecoration(
                    color: Color(0xD7FFFFFF), // Change this color to your desired background color
                    // Optional: To round the corners
                    border: Border.all(
                      width: 2,
                      color: Colors.black.withOpacity(0.30000001192092896),
                    ),

                    boxShadow: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 50,
                top: 460,
                child: Text(
                  '스케치선 만들기',
                  style: TextStyle(
                    color: Color(0xFF1C1C1C),
                    fontSize: 20,
                    fontFamily: 'Apple SD Gothic Neo',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              // Positioned(
              //   left: 54,
              //   top: 472,
              //   child: Text(
              //     '스케치 선 만들기 ',
              //     textAlign: TextAlign.center,
              //     style: TextStyle(
              //       color: Color(0xFFFFFFFF),
              //       fontSize: 10,
              //       fontFamily: 'Apple SD Gothic Neo',
              //       fontWeight: FontWeight.w400,
              //     ),
              //   ),
              // ),
              // Positioned(
              //   left: 237,
              //   top: 472,
              //   child: Text(
              //     '스케치 선 만들기 ',
              //     textAlign: TextAlign.center,
              //     style: TextStyle(
              //       color: Color(0xFF828282),
              //       fontSize: 10,
              //       fontFamily: 'Apple SD Gothic Neo',
              //       fontWeight: FontWeight.w400,
              //     ),
              //   ),
              // ),
              Positioned(
                left: 252,
                top: 460,
                child: Text(
                  '화풍 바꾸기',
                  style: TextStyle(
                    color: Color(0xFF1C1C1C),
                    fontSize: 20,
                    fontFamily: 'Apple SD Gothic Neo',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 67,
                top: 339,
                child: Container(
                  width: 91,
                  height: 82,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('images/sketch.png'),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),

              Positioned(
                left: 254,
                top: 339,
                child: GestureDetector(
                  onTap: () {
                    // Navigate to the ChangeStyle screen when clicked
                    Navigator.of(context).push(
                      MaterialPageRoute(builder: (context) => ChangeStyle()),
                    );
                  },
                child:Container(
                  width: 91,
                  height: 82,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('images/style-change.png'),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 390,
                  height: 92,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 390,
                          height: 46,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 308.67,
                                top: 17.33,
                                child: Container(
                                  width: 66.66,
                                  height: 11.34,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 42.33,
                                        top: 0,
                                        child: Container(
                                          width: 24.33,
                                          height: 11.33,
                                          child: Stack(children: [

                                          ]),
                                        ),
                                      ),
                                      // Positioned(
                                      //   left: 22.03,
                                      //   top: 0,
                                      //   child: Container(
                                      //     width: 15.27,
                                      //     height: 10.97,
                                      //     decoration: BoxDecoration(
                                      //       image: DecorationImage(
                                      //         image: NetworkImage("https://via.placeholder.com/15x11"),
                                      //         fit: BoxFit.fill,
                                      //       ),
                                      //     ),
                                      //   ),
                                      // ),
                                      // Positioned(
                                      //   left: 0,
                                      //   top: 0.34,
                                      //   child: Container(
                                      //     width: 17,
                                      //     height: 10.67,
                                      //     decoration: BoxDecoration(
                                      //       image: DecorationImage(
                                      //         image: NetworkImage("https://via.placeholder.com/17x11"),
                                      //         fit: BoxFit.fill,
                                      //       ),
                                      //     ),
                                      //   ),
                                      // ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17,
                        top: 66,
                        child: Container(
                          width: 113,
                          height: 26,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 26,
                                top: 4,
                                child: Container(
                                  width: 87,
                                  height: 18,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF4065DE),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(14),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 34,
                                top: 5,
                                child: SizedBox(
                                  width: 79,
                                  height: 15,
                                  child: Text(
                                    'Art Transfer',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 12,
                                      fontFamily: 'Apple SD Gothic Neo',
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}